Traceback (most recent call last):
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

def funky_func(x,y):
    return 3*(1-x)**2*np.exp(-x**2-(y+1)**2)-10*(x/5-x**3-y**5)*np.exp(-x**2-y**2)-(1/3)*np.exp(-(x+1)**2-y**2)

N = 40


z = np.zeros((N, N))

x_array = np.linspace(-4, 4, N)
print("x_array:", x_array)
                  
y_array = np.linspace(-4, 4, N)
print("y_array:", y_array)

for i in range(N):
    for j in range(N):
        x = x_array[i]
        y = y_array[j]
                  
        z[i,j] = funky_func(x, y)
    
print("sphere:\n", sphere)

plt.imshow(sphere)

fig = plt.figure(figsize=(6,6))
x1, y1 = np.meshgrid(x_array, y_array)
ax = fig.add_subplot(projection='3d')


# Plot the surface
ax.plot_surface(x1, y1, z)

# Set an equal aspect ratio
#ax.set_aspect('equal')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_35144\2321466637.py[0m in [0;36m<module>[1;34m[0m
[0;32m     23[0m         [0mz[0m[1;33m[[0m[0mi[0m[1;33m,[0m[0mj[0m[1;33m][0m [1;33m=[0m [0mfunky_func[0m[1;33m([0m[0mx[0m[1;33m,[0m [0my[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     24[0m [1;33m[0m[0m
[1;32m---> 25[1;33m [0mprint[0m[1;33m([0m[1;34m"sphere:\n"[0m[1;33m,[0m [0msphere[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     26[0m [1;33m[0m[0m
[0;32m     27[0m [0mplt[0m[1;33m.[0m[0mimshow[0m[1;33m([0m[0msphere[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'sphere' is not defined
NameError: name 'sphere' is not defined

