Traceback (most recent call last):
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Ella Metcalfe\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = np.zeros(5)

x[0] = 10
print("x:", x)

for i in range(5):
    x[i+1] = x[i] + 0.1*x[i] 
    
print("x:", x)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_27156\3670759407.py[0m in [0;36m<cell line: 6>[1;34m()[0m
[0;32m      5[0m [1;33m[0m[0m
[0;32m      6[0m [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[1;36m5[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m     [0mx[0m[1;33m[[0m[0mi[0m[1;33m+[0m[1;36m1[0m[1;33m][0m [1;33m=[0m [0mx[0m[1;33m[[0m[0mi[0m[1;33m][0m [1;33m+[0m [1;36m0.1[0m[1;33m*[0m[0mx[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m [1;33m[0m[0m
[0;32m      9[0m [0mprint[0m[1;33m([0m[1;34m"x:"[0m[1;33m,[0m [0mx[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mIndexError[0m: index 5 is out of bounds for axis 0 with size 5
IndexError: index 5 is out of bounds for axis 0 with size 5

