Traceback (most recent call last):
  File "C:\Users\ucqss\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\ucqss\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ucqss\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ucqss\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ucqss\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ucqss\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ucqss\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ucqss\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
axis = plt.axes(xlim =(-3, 3),ylim =(-1, 7))
line, = axis.plot([], [], lw = 2)
plt.close()

vals = range(5,30,2)

def init():
	line.set_data([], [])
	return line,

# animation function
def animate(i):
	x = np.linspace(-3,3,vals[i])
	y=x**2
	line.set_data(x, y)
	return line,

# calling the animation function
anim = animation.FuncAnimation(fig, animate,
							init_func = init,
							frames = len(vals),
							interval = 200,
							blit = True)

# saves the animation in our desktop
#anim.save('growingCoil.mp4', writer = 'ffmpeg', fps = 30)

# Note: below is the part which makes it work on Colab
rc('animation', html='jshtml')

anim
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 34>[1;34m()[0m
[0;32m     24[0m anim [38;5;241m=[39m animation[38;5;241m.[39mFuncAnimation(fig, animate,
[0;32m     25[0m 							init_func [38;5;241m=[39m init,
[0;32m     26[0m 							frames [38;5;241m=[39m [38;5;28mlen[39m(vals),
[0;32m     27[0m 							interval [38;5;241m=[39m [38;5;241m200[39m,
[0;32m     28[0m 							blit [38;5;241m=[39m [38;5;28;01mTrue[39;00m)
[0;32m     30[0m [38;5;66;03m# saves the animation in our desktop[39;00m
[0;32m     31[0m [38;5;66;03m#anim.save('growingCoil.mp4', writer = 'ffmpeg', fps = 30)[39;00m
[0;32m     32[0m 
[0;32m     33[0m [38;5;66;03m# Note: below is the part which makes it work on Colab[39;00m
[1;32m---> 34[0m [43mrc[49m([38;5;124m'[39m[38;5;124manimation[39m[38;5;124m'[39m, html[38;5;241m=[39m[38;5;124m'[39m[38;5;124mjshtml[39m[38;5;124m'[39m)
[0;32m     36[0m anim

[1;31mNameError[0m: name 'rc' is not defined
NameError: name 'rc' is not defined

