Traceback (most recent call last):
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

n_days = 100
b = 0.00005

I = np.zeros(n_days)
I[0] = 100
I = np.zeros(n_days)
S[0] = 0

for i in range(n_days - 1):
    I[i+1] = I[i] + b*S[i]+I[i]- 0.1 * I[i]
    S[i+1] = S[i] - b*S[i]+I[i]

plt.figure(figsize=(5,5))
plt.plot(I)
plt.plot(S)
plt.xlabel("Time (days)")
plt.ylabel("Population")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32mC:\Users\NATSCI~1\AppData\Local\Temp/ipykernel_29132/1275441938.py[0m in [0;36m<module>[1;34m[0m
[0;32m      7[0m [0mI[0m[1;33m[[0m[1;36m0[0m[1;33m][0m [1;33m=[0m [1;36m100[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m [0mI[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mzeros[0m[1;33m([0m[0mn_days[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 9[1;33m [0mS[0m[1;33m[[0m[1;36m0[0m[1;33m][0m [1;33m=[0m [1;36m0[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     10[0m [1;33m[0m[0m
[0;32m     11[0m [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mn_days[0m [1;33m-[0m [1;36m1[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'S' is not defined
NameError: name 'S' is not defined

