Traceback (most recent call last):
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Ella Metcalfe\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def fdiff(f,xRange,step):
    
    #Construct datapoints (x,y=f(x))
    xmin,xmax=xRange
    stop=xmax+2*step
    x = np.arange(xmin,stop,step)
    y = f(x)

    #Apply finite difference formula
    ydiff = y[1:]-y[0:-1]
    xdiff = x[1:]-x[0:-1]
    yd = ydiff/xdiff
    
    #Return derivative datapoints
    return x[0:-1],y[0:,-1],yd

x,y,yd=fdiff(y,[-pi,pi],1e-3)

fig, ax = plt.subplots(1,2)
ax[0].plot(x,y)
ax[1].plot(x,yd)
plt.show()

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12020\3627838409.py[0m in [0;36m<cell line: 17>[1;34m()[0m
[0;32m     15[0m     [1;32mreturn[0m [0mx[0m[1;33m[[0m[1;36m0[0m[1;33m:[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[0my[0m[1;33m[[0m[1;36m0[0m[1;33m:[0m[1;33m,[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[0myd[0m[1;33m[0m[1;33m[0m[0m
[0;32m     16[0m [1;33m[0m[0m
[1;32m---> 17[1;33m [0mx[0m[1;33m,[0m[0my[0m[1;33m,[0m[0myd[0m[1;33m=[0m[0mfdiff[0m[1;33m([0m[0my[0m[1;33m,[0m[1;33m[[0m[1;33m-[0m[0mpi[0m[1;33m,[0m[0mpi[0m[1;33m][0m[1;33m,[0m[1;36m1e-3[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     18[0m [1;33m[0m[0m
[0;32m     19[0m [0mfig[0m[1;33m,[0m [0max[0m [1;33m=[0m [0mplt[0m[1;33m.[0m[0msubplots[0m[1;33m([0m[1;36m1[0m[1;33m,[0m[1;36m2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp\ipykernel_12020\3627838409.py[0m in [0;36mfdiff[1;34m(f, xRange, step)[0m
[0;32m     13[0m [1;33m[0m[0m
[0;32m     14[0m     [1;31m#Return derivative datapoints[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 15[1;33m     [1;32mreturn[0m [0mx[0m[1;33m[[0m[1;36m0[0m[1;33m:[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[0my[0m[1;33m[[0m[1;36m0[0m[1;33m:[0m[1;33m,[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[0myd[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     16[0m [1;33m[0m[0m
[0;32m     17[0m [0mx[0m[1;33m,[0m[0my[0m[1;33m,[0m[0myd[0m[1;33m=[0m[0mfdiff[0m[1;33m([0m[0my[0m[1;33m,[0m[1;33m[[0m[1;33m-[0m[0mpi[0m[1;33m,[0m[0mpi[0m[1;33m][0m[1;33m,[0m[1;36m1e-3[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mIndexError[0m: too many indices for array: array is 1-dimensional, but 2 were indexed
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

