Traceback (most recent call last):
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Ella Metcalfe\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Ella Metcalfe\anaconda3\lib\site-packages\nbclient\client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import mpmath as mp
import matplotlib.pyplot as plt
mp.dps = 15;
hk=[10.0**-n for n in range(1,15)]
e=[mp.cos(mp.pi/3)-mp.diff(mp.sin,mp.pi/3,hk=10.0**-n, direction=1) for n in range(1,15)]
plt.loglog(hk,e,'o')

plt.xlabel("step size $h_k$")
plt.ylabel("error")
plt.gca()/invert_xaxis()
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_7756\2115784517.py[0m in [0;36m<cell line: 10>[1;34m()[0m
[0;32m      8[0m [0mplt[0m[1;33m.[0m[0mxlabel[0m[1;33m([0m[1;34m"step size $h_k$"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [0mplt[0m[1;33m.[0m[0mylabel[0m[1;33m([0m[1;34m"error"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 10[1;33m [0mplt[0m[1;33m.[0m[0mgca[0m[1;33m([0m[1;33m)[0m[1;33m/[0m[0minvert_xaxis[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [0mplt[0m[1;33m.[0m[0mshow[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'invert_xaxis' is not defined
NameError: name 'invert_xaxis' is not defined

